name: C/C++ CI with GoogleTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y libgtest-dev
        sudo apt-get install -y cmake
        sudo apt-get install -y googletest
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Build main program
      run: |
        make main
        echo "Main program built successfully"

    - name: Build tests
      run: |
        make test
        echo "Tests built successfully"

    - name: Run tests
      run: |
        make run-tests
        echo "All tests passed successfully!"

    - name: Clean build artifacts
      run: make clean

    - name: Verify files exist
      run: |
        ls -la
        echo "Current directory contents:"
        pwd
